/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero  ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/BriefHQ/drizzle-zero        ##
 * ------------------------------------------------------------
 */

export type Simplify<T> = T & {};
export type Schema = {
  readonly tables: {
    tableOne: {
      name: "tableOne";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly options: {
          type: "json";
          customType: {
            name: string;
          };
          optional: true;
        };
      };
    };
    tableTwo: {
      name: "tableTwo";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly options: {
          type: "json";
          customType: {
            name: string;
          };
          optional: true;
        };
      };
    };
    tableThree: {
      name: "tableThree";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly options: {
          type: "json";
          customType: Simplify<import("./types").OptionsThree>;
          optional: true;
        };
      };
    };
    tableFour: {
      name: "tableFour";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly options: {
          type: "json";
          customType: Simplify<import("../../../../types").OptionsFour>;
          optional: true;
        };
      };
    };
    tableFive: {
      name: "tableFive";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly options: {
          type: "json";
          customType: Simplify<import("../../../shared/src").OptionsFive>;
          optional: true;
        };
      };
    };
    tableSix: {
      name: "tableSix";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly options: {
          type: "json";
          customType: Simplify<import("./types").OptionsThree>;
          optional: true;
        };
      };
    };
  };
  readonly relationships: {};
};

export const schema = {
  "tables": {
    "tableFive": {
      "name": "tableFive",
      "columns": {
        "id": {
          "type": "string",
          "optional": false,
          "customType": null as unknown
        },
        "options": {
          "type": "json",
          "optional": true,
          "customType": null as unknown
        }
      },
      "primaryKey": [
        "id"
      ],
      "serverName": "table_five"
    },
    "tableFour": {
      "name": "tableFour",
      "columns": {
        "id": {
          "type": "string",
          "optional": false,
          "customType": null as unknown
        },
        "options": {
          "type": "json",
          "optional": true,
          "customType": null as unknown
        }
      },
      "primaryKey": [
        "id"
      ],
      "serverName": "table_four"
    },
    "tableOne": {
      "name": "tableOne",
      "columns": {
        "id": {
          "type": "string",
          "optional": false,
          "customType": null as unknown
        },
        "options": {
          "type": "json",
          "optional": true,
          "customType": null as unknown
        }
      },
      "primaryKey": [
        "id"
      ],
      "serverName": "table_one"
    },
    "tableSix": {
      "name": "tableSix",
      "columns": {
        "id": {
          "type": "string",
          "optional": false,
          "customType": null as unknown
        },
        "options": {
          "type": "json",
          "optional": true,
          "customType": null as unknown
        }
      },
      "primaryKey": [
        "id"
      ],
      "serverName": "table_six"
    },
    "tableThree": {
      "name": "tableThree",
      "columns": {
        "id": {
          "type": "string",
          "optional": false,
          "customType": null as unknown
        },
        "options": {
          "type": "json",
          "optional": true,
          "customType": null as unknown
        }
      },
      "primaryKey": [
        "id"
      ],
      "serverName": "table_three"
    },
    "tableTwo": {
      "name": "tableTwo",
      "columns": {
        "id": {
          "type": "string",
          "optional": false,
          "customType": null as unknown
        },
        "options": {
          "type": "json",
          "optional": true,
          "customType": null as unknown
        }
      },
      "primaryKey": [
        "id"
      ],
      "serverName": "table_two"
    }
  },
  "relationships": {}
} as Schema;
